/** This file was autogenerated by Haiku at 20170716113501. */
import React from 'react' // Installed as a peer dependency of '@haiku/core'
import ReactDOM from 'react-dom' // Installed as a peer dependency of '@haiku/core'
import HaikuReactAdapter from '@haiku/core/dom/react/index.js'
import domModule from './dom.js'
var React_SuperComplex = HaikuReactAdapter(domModule)
if (React_SuperComplex.default) React_SuperComplex = React_SuperComplex.default
export default React_SuperComplex